---
# defaults file for ansible-jmeter
jmeter_user: jmeter
jmeter_version: 5.6.2
jmeter_installation_path: /opt/jmeter

jmeter_epel_url: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm'
python_pip_package: >-
  {{ (ansible_facts.python.version.major|int == 3)
      | ternary('python3-pip', 'python-pip') }}

__java_packages:
  - java-11-openjdk